[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonk_squad_log = "APozxuLZW4crR9nTPzQJEUpWMLubeC3bBUWs7ewCwtPE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lyte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
